### ISSUE TITLE
Issue references

### ISSUE THREAD

**Issue by FastGeert** [gigforks/gitea#10]
In the top of an issue page below Milestone, i want to have a list of referenced issues to the currently displayed issue.

**Comment by arahmanhamdy** [comment]
There is no issue referencing in markdown for gogs and gitea.

**Comment by FastGeert** [comment]
I am not talking about markdown. I just want to match on the markdown contents for references to other issues, register these in the database, and display them.

**Comment by arahmanhamdy** [comment]
The issue references can be in any of these forms:
`#16` => refers to issue no 16 in the same repo
`Owner/Repo#16` => refers to issue no 16 in the owner's `Owner` repo `Repo` 
`https://github.com/gigforks/gitea/issues/6` => refers to external issue from github

We can use any of these in issue body or comments and the issue will be listed in references sidebar section

**Comment by Dinaamagdy** [comment]
# testing scenarios : 
- create issue with reference to another issue in (same repo - another repo in gitea-  github one )
- comment with reference to another issue in (same repo - another repo in gitea-  github one ) 
- comment with issue in repo, this user  doesn't have access on it 
## Software version 
60c4fcc3b6b83ac8c7509060485fe196653e0d44
