### ISSUE TITLE
Register screen should point to IYO too

### ISSUE THREAD

**Issue by ghost** [gigforks/gitea#11]
Right now the page just request standard stuff (Username, Email, Password) but we want to direct people to IYO. 

Add a message on the registration page that they should be using ITSYOU.ONLINE to login (with link).

**Comment by Dinaamagdy** [comment]
there is no registration page available now , only sign in option with itsyou.online
## Software Version 
f76784f3c51474c9dca3e5bf3ed3b5a1a3baba2e
