### ISSUE TITLE
Remake linking with IYO page 

### ISSUE THREAD

**Issue by ghost** [gigforks/gitea#13]
Right now if I click login with IYO I am taken to IYO then I am taken back to gitea and presented with this page:
![authorize iyo no comments](https://user-images.githubusercontent.com/31761294/32894849-c86b3588-cae6-11e7-9b92-6ec31b7b8a61.jpg)

It's too confusing. It's just a link page but it's so hard to navigate. 

We need to change it so it clearly reflects that they are linking the account to IYO.

Suggested modification:
![authorize iyo adnotated](https://user-images.githubusercontent.com/31761294/32895059-7409aa64-cae7-11e7-8c9b-b8f8d08d0d07.jpg)

The first panel doesn't need to exist. The functionality in it is doubled by the signup panel below. They're both taking in username and password. If the username and password already exist in the gitea database then it can be linked to an IYO account.

Text needs to be more descriptive:
Username -> Username to display on gitea
Password -> Password for gitea
(so people don't confuse it with the IYO password)
Re-Type -> Re-Type Password

Button needs to be changed from "Create Account" to "Link to ITSYOU.ONLINE"

**Comment by Dinaamagdy** [comment]
f76784f3c51474c9dca3e5bf3ed3b5a1a3baba2e
