### ISSUE TITLE
problem in sign out in multi tabs

### ISSUE THREAD

**Issue by Dinaamagdy** [gigforks/gitea#16]
## Steps 
- sign in in two tabs 
- sign out in one of them
## Issue 
- try to sight out in the other tab will redirect you to not working page as shown 
![selection_589](https://user-images.githubusercontent.com/24386802/33269677-3a3021c8-d38a-11e7-963c-af86f08b293c.png)

## Software Version 
f76784f3c51474c9dca3e5bf3ed3b5a1a3baba2e
on iyo_cleanup

**Comment by Dinaamagdy** [comment]
## Software version 
33648f9a0b9b41fc2f2bda0638ac783a96ebbdc4

**Comment by arahmanhamdy** [comment]
Reopened issue to reverify it after changes done in 1050c883aebf6408db0418cc1ac09a55daee04ed

**Comment by Dinaamagdy** [comment]
## Software Version 
b7de394df022569ca2dfcce0962fb5f651f26145
