### ISSUE TITLE
Admin user can convert user from itsyou.online user to local user 

### ISSUE THREAD

**Issue by Dinaamagdy** [gigforks/gitea#19]
## Issue 
for admin user from admin setting ,he can change another user to be from it'syouonline user to local user , so u can't login with this user again , but u can't use it's name or email !
![selection_596](https://user-images.githubusercontent.com/24386802/33374166-ac7dc0f8-d50d-11e7-827e-8ff83ebfd282.png)

**Comment by FastGeert** [comment]
This is not a problem. Its a feature, not a bug.
