### ISSUE TITLE
Investigate gogs to gitea migration procedure

### ISSUE THREAD

**Issue by LeeSmet** [gigforks/gitea#2]

**Comment by LeeSmet** [comment]
Migrating succeeded with a small example setup following the steps [on the official gitea docs](https://docs.gitea.io/en-us/upgrade-from-gogs/). The gogs was build from the itsyouimpl branch, db version 14.

**Comment by Dinaamagdy** [comment]
In the migeration of gogs there http://212.23.52.76:4000
I found that there is repo called ThreeFold but when I try to get it I get not found page , so If I don't have access in repo it should not  appear in  repositories 
![selection_591](https://user-images.githubusercontent.com/24386802/33275980-db8cd586-d39c-11e7-8c00-914968682fe3.png)
![selection_591](https://user-images.githubusercontent.com/24386802/33275985-ddcd0b4a-d39c-11e7-95d5-053ab550fa5e.png)

**Comment by Dinaamagdy** [comment]
## Software version 
33648f9a0b9b41fc2f2bda0638ac783a96ebbdc4
