### ISSUE TITLE
Broken search results

### ISSUE THREAD

**Issue by arahmanhamdy** [gigforks/gitea#21]
## Description

The user profile repository search, returns broken links

## Screenshots

![screenshot-2017-11-29 ahamdy](https://user-images.githubusercontent.com/7352583/33375874-1439bffc-d514-11e7-9abf-79197623b7df.png)

**Comment by Dinaamagdy** [comment]
## Software Version 
b7de394df022569ca2dfcce0962fb5f651f26145
