### ISSUE TITLE
Loose the username configuration step at first login

### ISSUE THREAD

**Issue by FastGeert** [gigforks/gitea#23]
Currently after logging in for the first time people need to setup their username / password.

This is only needed for https access to the git repo's, and is not needed.

Also, disable https cloning of git repo's

**Comment by arahmanhamdy** [comment]
loose username config fixed by commit 9f20e3c 
For https clone disable, it is already implemented in gitea by default. we just need to add this section in custom/conf/app.ini

```
[repository]
DISABLE_HTTP_GIT = true
```
