### ISSUE TITLE
Cannot assign to members of organisation

### ISSUE THREAD

**Issue by FastGeert** [gigforks/gitea#24]
![image](https://user-images.githubusercontent.com/15246294/34051310-634f41a0-e1be-11e7-9af7-ffea3ba4f43d.png)

As you can see i can only assign issues to Kristof = created the repo & Myself, added the issue. But I want to assign it to Hamdy who also has access to this repo

**Comment by Dinaamagdy** [comment]
## Software Version 
0d70e7cd114a01aa98aeda7837e4d12b92f945da
