### ISSUE TITLE
name of users too long 

### ISSUE THREAD

**Issue by Dinaamagdy** [gigforks/gitea#27]
As shown in following screenshot , name of users too long , so you can't see then name of repos , even u select it 
![selection_001](https://user-images.githubusercontent.com/24386802/34251860-1b2e2ae0-e64a-11e7-909c-79839525d9a7.png)

## Software version 
0d70e7cd114a01aa98aeda7837e4d12b92f945da

**Comment by arahmanhamdy** [comment]
Also using emails prevents users from being mentioned using `@`
![screenshot-2017-12-25 itenv_docs_grid_tf](https://user-images.githubusercontent.com/7352583/34336320-c5269c1e-e95e-11e7-91cc-80f6d8f66f3e.png)

**Comment by FastGeert** [comment]
weynand@greenitglobe.com should become weynand

if there is already another weynand, then weynand@greeinitglobe.com becomes weynand1

Don't forget to also create a sql migration to cleanup existing usernames.

**Comment by arahmanhamdy** [comment]
1 - Rename all repo dirs to new short names:
```
cd GIT_REPOS_DIR
for f in *; do
    if [[ $f == *"@"* ]]; then
           IFS='@' read -r -a array <<< "$f"; 
           mv "$f" "${array[0]}"; 
    fi
done 
```
2 - update user table from SQL: 
```SQL
update "user" set lower_name = split_part(email, '@', 1), name=split_part(email, '@', 1) where lower_name ilike '%@%'; 
```

**Comment by Dinaamagdy** [comment]
## Software Version 
45202eae46b4ba34900f9c9bec45bd3de2c524c7
