### ISSUE TITLE
Can't open any Wiki File on repos since migration to Gitea 

### ISSUE THREAD

**Issue by arahmanhamdy** [gigforks/gitea#39]
Related issue: 
https://docs.greenitglobe.com/gig/org_support/issues/506

**Comment by Dinaamagdy** [comment]
## Steps 
- Try to open one of the existing files and edit it.
- Try to delete one of existing files .

## Issue 
delete and edit redirect you  to 500 page ,although if you create new file and try to edit or delete it will work normally

**Comment by arahmanhamdy** [comment]
Opened new separate issue for delete and edit:
https://github.com/gigforks/gitea/issues/41
