### ISSUE TITLE
Investigate panic if there are no itsyouonline organizations

### ISSUE THREAD

**Issue by LeeSmet** [gigforks/gitea#4]
[Macaron] PANIC: interface conversion: interface {} is nil, not []string
/usr/local/go/src/runtime/panic.go:489 (0x42a8cf)
/usr/local/go/src/runtime/iface.go:172 (0x40d5a1)
/Users/rob/workspace/go/src/github.com/gogits/gogs/routers/api/v1/repo/collaborators_extended.go:33 (0xc23735)

**Comment by Dinaamagdy** [comment]
## Software Version 
f76784f3c51474c9dca3e5bf3ed3b5a1a3baba2e 
on iyo_cleanup
