### ISSUE TITLE
Itsyouonline organisation integration does not work

### ISSUE THREAD

**Issue by FastGeert** [gigforks/gitea#7]
I added write access for members in the itsyouonline organisation *test2* to my repository. However if people login on gitea that are member of *test2*, they do not get access to my repository.

![image](https://user-images.githubusercontent.com/15246294/32831719-80b4c6e8-c9f9-11e7-8cd7-1b38a6b6e253.png)

**Comment by arahmanhamdy** [comment]
The organization added to the repo must be the same as the org used for authentication or a child of it so that it can identify whether the user is a member of it or not.
the current org used with the test server is : `threefold`

**Comment by FastGeert** [comment]
Ok, understood, but then the system should not allow organisations to be used that are not equal to or be a child of the organisation that is used to authenticate people towards.

**Comment by arahmanhamdy** [comment]
Now if you added an organization that doesn't belong to the main organization it will raise error:

![screenshot-2017-11-20 greenit_private](https://user-images.githubusercontent.com/7352583/33019373-ae860840-ce02-11e7-85e3-9bb726bb4182.png)

**Comment by Dinaamagdy** [comment]
## Software Version
f76784f3c51474c9dca3e5bf3ed3b5a1a3baba2e

**Comment by arahmanhamdy** [comment]
Reopened issue to reverify it after changes done in 1050c883aebf6408db0418cc1ac09a55daee04ed

**Comment by Dinaamagdy** [comment]
## Software Version 
0d70e7cd114a01aa98aeda7837e4d12b92f945da
