### ISSUE TITLE
Full text search 

### ISSUE THREAD

**Issue by FastGeert** [gigforks/gitea#9]
Need a way to do full text search on tickets cross repositories on which i have access.

**Comment by arahmanhamdy** [comment]
The fix depends on using `tsvector` in `postgresql` so we need to stick to use `postgresql` as the database engine.

**Comment by Dinaamagdy** [comment]
search with full title of issue , redirect me to wrong page with 500 as shown 
![image](https://user-images.githubusercontent.com/24386802/34246069-b2723578-e635-11e7-8282-38a8853b8dbf.png)
## Software Version 
b7de394df022569ca2dfcce0962fb5f651f26145

**Comment by FastGeert** [comment]
QA pls test for the following:
- search on issue title
- search on issue comment
- search on users 
- search on wiki contents
- search on repo / organization names

Results should be url's with a bit of context (like google):
- organizations
- repos
- users
- wiki pages 
- issues

**Comment by FastGeert** [comment]
If the full text search does not offer above complete set yet. This should not hold us back to upgrade our gitea's, so that we can start using the kanban functions

**Comment by Dinaamagdy** [comment]
the search now , only work on : 
- search on issue title
- search on issue content (the actual content of issue )not comments of issue

**Comment by Dinaamagdy** [comment]
search in search box in isues page appear also in full box search as shown
![selection_610](https://user-images.githubusercontent.com/24386802/34932196-9cf38892-f9da-11e7-82d6-5fe8ccf54b8c.png)

**Comment by Dinaamagdy** [comment]
another test scenario which fail : 
- search in full text search box with private repo name which this user doesn't have access to it
## Issue 
this private repo will appear but if you  try get it , will result 404  : 
![selection_612](https://user-images.githubusercontent.com/24386802/34938659-de7fea64-f9f1-11e7-946f-384384c152f5.png)
![Uploading Selection_611.png…]()

**Comment by Dinaamagdy** [comment]
search for  code , result some empty pages as shown : 
![selection_614](https://user-images.githubusercontent.com/24386802/34944089-e24ff32c-fa06-11e7-8f53-cf4d632c514f.png)

**Comment by Dinaamagdy** [comment]
pages in the result issues doesn't work , as example there are three pages in the shown image but all same issues 
![selection_617](https://user-images.githubusercontent.com/24386802/34944278-9eb2221a-fa07-11e7-97c3-feb55b18f453.png)

![selection_616](https://user-images.githubusercontent.com/24386802/34944282-a146fcbc-fa07-11e7-8180-da37e0211933.png)

**Comment by Dinaamagdy** [comment]
almost features finished except 
- some issues for code full text search https://github.com/gigforks/gitea/issues/45: 
1 - If the file has unescaped html it will brake the result
2 - The result should have repo name 
3 - the number of results is inconsistent in some cases (randomly)
- search on wiki contents https://github.com/gigforks/gitea/issues/44
